[system]
port = ":1234"

[dbDefault]
dbType = "mysql"
dbHost = "localhost" #数据库连接地址
dbName = "phalgo"         #数据库名称
dbUser = "root"            #数据库用户名
dbPasswd = "iloveyou11"  #数据库密码
dbPort = "3306"               #数据库端口号
dbOpenconns_max = 20           #最大连接数
dbIdleconns_max = 0            #最大空闲连接
